### ISSUE TITLE
Request for CC-3M Dataset Pre-trained Model Parameters

### ISSUE THREAD

**Issue by ethanAiJLu** [xmed-lab/CLIPN#2]
Highly appreciate your work and would like to explore new models in your research. However, I lack sufficient computational power for pre-training. May I inquire if you could provide the pre-trained model parameters for the CC-3M dataset? Thank you very much.

**Comment by SiLangWHL** [comment]
Hi, thanks for your interest in our paper. The ViT-B-16-based CLIPN pre-trained on CC3M has been published in the section "Reproduced Results" of the README file. You can download and evaluate them on your own device. I am extending CLIPN to more models, such as ViT-L and ViT-B-32. If you are interested, please kindly stay tuned for further updates! 

Free feel to contact me if you have other questions.

Bests,
Hualiang
