### ISSUE TITLE
Where to download the trained weights of CLIPN?

### ISSUE THREAD

**Issue by jyC23333** [xmed-lab/CLIPN#6]
Hi, I'm going to test my own datasets of CLIPN, but didn't see any links to download the weights of CLIPN. 
How could I get the weights?

**Comment by SiLangWHL** [comment]
Hi, you can find the pre-trained CLIPN model in the Table in the Section. Reproduced Results of README.md. 
![1703063336851](https://github.com/xmed-lab/CLIPN/assets/33173982/a39e81b3-f840-4230-84ca-55a1a8c4e04d)

**Comment by jyC23333** [comment]
Thanks so much!
