### ISSUE TITLE
Weights for the ViT-B-32 model

### ISSUE THREAD

**Issue by ybendou** [xmed-lab/CLIPN#8]
Hello, 

Thank you for the interesting work! Could you provide the weights for the ViT-B-32 model? 
Only the ViT-B-16 version is available in the README.

Thanks in advance!
Best,

**Comment by ybendou** [comment]
Hello, 
Could you please provide the weights for the ViT-B-32 model?
I would really appreciate it! 

Thanks in advance, 
Best

**Comment by SiLangWHL** [comment]
Hi,
Sorry for the late reply. I've sent you the counterweight linkage, yes? I will release them recently.

**Comment by SiLangWHL** [comment]
Hi,
Sorry for the late reply. I've sent you the linkage of weights, yes? I will release them recently.

**Comment by ybendou** [comment]
Hi, 
No worries, I received them! Thank you for sending them by email. I forgot to close the issue afterwards.
Best,

**Comment by X-funbean** [comment]
> Thank you for the interesting work! Could you provide the weights for the ViT-B-32 model?

Hi, can you sent me the linkage of ViT-B-32 weights as well? Many thanks! @SiLangWHL
